### PR TITLE
Use rich for displaying error traceback in mlinfra cli

### LINKED ISSUE #96: [Feature]: Add rich to mlinfra cli to allow better understanding of stacktrace
### Describe the Feature

[rich library](https://github.com/Textualize/rich) allows better terminal output. Rich can also render pretty tracebacks in case code runs into an exception

### Importance of the Feature

This improves the stacktrace reading capability of the code and allows users to understand the errors better.

### Additional context

_No response_

### Feature Category

mlinfra cli

### PR DESCRIPTION
**Pull request by ara-25**
## This PR proposes the following changes
- 
Closes #96 

### PR Checklist

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Tests

### CODE REVIEW

**Comment by aliabbasjaffri** [comment]
@ara-25 have you tested these changes? I tried to see rich based stacktrace, but that didn't work.

**Comment by ara-25** [comment]
> @ara-25 have you tested these changes? I tried to see rich based stacktrace, but that didn't work.

That's strange. Are you testing by running the `mlinfra` cli or some other module?

For me, the stack trace is showing upon running `mlinfra  estimate-cost abc.yml`

**Comment by aliabbasjaffri** [comment]
I'm testing it by trying to run the pyinvoke command directly, so by calling `pyinvoke estimate-cost abs.yaml`.

**Comment by ara-25** [comment]
So, with my current implementation, the `rich` traceback only appears in `mlinfra` command or if `cli.py` is run directly. This is because from the original issue, I understood that this feature only needs to be added for the mlinfra cli, instead of the entire codebase.

Please let me know if the formatted traceback needs to be displayed for the entire codebase and I will modify it accordingly.

**Comment by aliabbasjaffri** [comment]
Ah alright, that makes sense. 
Yes, the idea was to have this enabled for the entire codebase as it would be easier to spot where an error is coming from. It would be really cool if you can adjust it for the repo, or if you want i can create a new issue for that. Both are fine with me.

**Comment by ara-25** [comment]
@aliabbasjaffri would be great if a separate issue can be created for that :)

**Review by aliabbasjaffri — APPROVED** [review]

**Comment by aliabbasjaffri** [comment]
Just tested and verified. Thank you for your contribution. If you are interested in contributing further and extending rich to the rest of the codebase, do let me know.

**Comment by ara-25** [comment]
Thanks @aliabbasjaffri

I am interested on working further on integrating rich in mlinfra

**Comment by aliabbasjaffri** [comment]
hey @ara-25 , i managed to create a new issue for [rich integration across entire codebase](https://github.com/mlinfra-io/mlinfra/issues/143). Please let me know if you need any more context of help regarding this. You can reach out to me via discord channel, i'm rather fast to reply back there than on the github issues. 

Also, i would like to request a github ⭐ from you as that would really help the tool get more traction and users. Thank you!

**Comment by ara-25** [comment]
Thanks a lot @aliabbasjaffri. 

Also, I have already starred your amazing work

**Pull request merged**
